### ISSUE TITLE
Edit Liquid Standard

### ISSUE THREAD

**Issue by Marke45** [Marke45/lablog#12]
<img width="388" alt="Screenshot 2022-02-05 at 15 40 05" src="https://user-images.githubusercontent.com/31522005/152648454-9055bf64-ba73-4fba-a552-54ea6aa688f8.png">

Editing a standard doesn't work. 
Updating info does not save
Remove ability to edit logged_in_by and _date

**Comment by DACunningham** [comment]
This is my bad.  It asks for the opened by field to be filled in right?  I can fix this quickly.
