### ISSUE TITLE
Date format error checking

### ISSUE THREAD

**Issue by Marke45** [Marke45/lablog#20]
When inputting date to form, error-check for a viable date-format

**Comment by DACunningham** [comment]
This ^.  We can solve this by using components from bootstrap.  I'd suggest not getting too bogged down in trying to solve this with the field components that are on the front end (FE) now as I'd suggest that we need to do a fair bit of work on the FE anyway.  What do you think?

**Comment by DACunningham** [comment]
Having said that, the above is correct but we can add a date picker widget (knew Django was better than that) by specifying it in the form as below in the forms.py

https://stackoverflow.com/questions/3367091/whats-the-cleanest-simplest-to-get-running-datepicker-in-django
