### ISSUE TITLE
Nullable 'created_by' on workingsolutiontable

### ISSUE THREAD

**Issue by DACunningham** [Marke45/lablog#8]
'created_by' can be set to null in workingsolution table.  This relates to the issue we talked about with using ForeignKeys to relate a table to another in a 1-many reationship.  We want any 'logged_in_by' fields to be foreign keys to the 'user' 

![image](https://user-images.githubusercontent.com/17599985/152430655-62ee9db4-cafc-45dc-ba0a-e1438420dd0b.png)

**Comment by DACunningham** [comment]
Probably going to remove from the create working solution form as I am assuming created by is the curerntly logged in user and created date should be set on creation without leaving the ability for a user to change it.

![image](https://user-images.githubusercontent.com/17599985/152648097-2354a9c7-50e9-4e53-a486-d9d69f0139b6.png)

**Comment by Marke45** [comment]
Agreed. Removed Logged_in_date from the form
